datasource:
  postgres:
    url: jdbc:postgresql://172.47.7.1:5432/petclinic
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver    

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.47.7.11:8761/eureka/
      
spring.metrics.export.send-latest: false
spring.metrics.export.delay-millis: 30000